name: walewein
description: Easily track your consumption.
publish_to: 'none'

version: 0.6.3+12

environment:
  sdk: '>=2.18.1 <3.0.0'

isar_version: &isar_version 3.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  # State and database
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  provider: ^6.0.4

  # UI
  smooth_page_indicator: ^1.0.0+2
  auto_size_text: ^3.0.0
  dots_indicator: ^2.1.0
  fl_chart: ^0.55.2
  bottom_bar_with_sheet: ^2.4.0
  cupertino_icons: ^1.0.2

  # Localization
  easy_localization: ^3.0.1
  intl: ^0.17.0

  # File handling
  image_picker: ^0.8.5+3
  file_picker: ^5.2.3
  path_provider: ^2.0.11
  flutter_file_dialog: ^2.3.2

  # Varia
  google_mlkit_text_recognition: ^0.4.0
  flutter_displaymode: ^0.4.0
  equations: ^4.1.0
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.6
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: any
  flutter_launcher_icons: "^0.10.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/translations/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Bold.ttf
          weight: 700
        - asset: fonts/Mulish-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
