name: walewein
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

isar_version: &isar_version 3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  google_mlkit_text_recognition: ^0.4.0
  bottom_bar_with_sheet: ^2.4.0
  intl: ^0.17.0
  flutter_displaymode: ^0.4.0
  dots_indicator: ^2.1.0
  fl_chart: ^0.55.2
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: any

flutter:
  uses-material-design: true